language: objective-c
osx_image: xcode9
script:
 - xcodebuild -project ./iOS/Swift/ProductsMVP.xcodeproj -scheme ProductsMVPTests test -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0'
 - xcodebuild -project ./iOS/Swift/ProductsMVP.xcodeproj -scheme ProductsMVP clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

